<?php

namespace App\Actions;

use App\Helpers\PardisanHelper;
use App\Models\SurveyAnswerModel;
use App\Models\SurveyOptionModel;
use Genocide\Radiocrud\Exceptions\CustomException;
use Genocide\Radiocrud\Services\ActionService\ActionService;
use App\Models\SurveyCategoryModel;
use App\Http\Resources\SurveyCategoryResource;

class SurveyCategoryAction extends ActionService
{
    public function __construct()
    {
        $this
            ->setModel(SurveyCategoryModel::class)
            ->setResource(SurveyCategoryResource::class)
            ->setValidationRules([
                'store' => [
                    'text' => ['required', 'string', 'max:20000'],
                    'is_active' => ['boolean'],
                    'type' => ['required', 'in:teacher,student'],
                    'educational_year' => ['string', 'max:20']
                ],
                'update' => [
                    'text' => ['string', 'max:20000'],
                    'is_active' => ['boolean'],
                    'educational_year' => ['string', 'max:20']
                ],
                'get' => [
                    'student_id' => ['integer'],
                    'type' => ['in:student,teacher'],
                    'is_active' => ['boolean'],
                    'educational_year' => ['string', 'max:20']
                ],
                'getByStudent' => [
                    'is_active' => ['boolean'],
                    'educational_year' => ['string', 'max:20']
                ],
                'getByTeacher' => [
                    'is_active' => ['boolean'],
                    'educational_year' => ['string', 'max:20']
                ],
            ])
            ->setQueryToEloquentClosures([
                'type' => function (&$eloquent, $query)
                {
                    $eloquent = $eloquent->where('type', $query['type']);
                },
                'is_active' => function (&$eloquent, $query)
                {
                    $eloquent = $eloquent->where('is_active', $query['is_active']);
                },
                'has_answered' => function (&$eloquent, $query)
                {
                    $user_id = $query['student_id'] ?? $query['teacher_id'] ?? null;
                    if ($query['has_answered'])
                        $eloquent = $eloquent->whereHas('surveyAnswers', function ($q) use($query, $user_id){
                            $q->where('participant_id', $user_id);
                        });
                    else
                        $eloquent = $eloquent->whereDoesntHave('surveyAnswers', function ($q) use($query, $user_id){
                            $q->where('participant_id', $user_id);
                        });
                },
                'educational_year' => function(&$eloquent, $query)
                {
                    if($query['educational_year'] != '*')
                        $eloquent = $eloquent->where('educational_year', $query['educational_year']);
                }
            ]);
        parent::__construct();
    }

    public function store(array $data, callable $storing = null): mixed
    {
        if(!isset($data['educational_year']))
            $data['educational_year'] = PardisanHelper::getCurrentEducationalYear();

        return parent::store($data, $storing); // TODO: Change the autogenerated stub
    }
}
