<?php

namespace App\Actions;

use App\Http\Resources\TeacherSkillResource;
use App\Models\TeacherSkillModel;
use App\Models\TeacherWorkExperienceModel;
use Genocide\Radiocrud\Exceptions\CustomException;
use Genocide\Radiocrud\Services\ActionService\ActionService;
use Illuminate\Http\Request;

class TeacherWorkExperienceAction extends ActionService
{
    public function __construct()
    {
        $this
            ->setModel(TeacherWorkExperienceModel::class)
            ->setResource(TeacherSkillResource::class)
            ->setValidationRules([
                'storeByAdmin' => [
                    'teacher_id' => ['required', 'string', 'max:20'],
                    'title' => ['required', 'string', 'max:350'],
                    'workplace_name' => ['string', 'max:350'],
                    'work_title' => ['string', 'max:350'],
                    'current_status' => ['string', 'max:350'],
                    'reason_for_the_termination_of_cooperation' => ['string', 'max:350'],
                    'workplace_location' => ['string', 'max:350'],
                ],
                'update' => [
                    // 'teacher_id' => ['string', 'max:20'],
                    'title' => ['string', 'max:350'],
                    'workplace_name' => ['string', 'max:350'],
                    'work_title' => ['string', 'max:350'],
                    'current_status' => ['string', 'max:350'],
                    'reason_for_the_termination_of_cooperation' => ['string', 'max:350'],
                    'workplace_location' => ['string', 'max:350'],
                ],
                'get_query' => [
                    'search' => ['string', 'max:255'],
                ]
            ])
            ->setQueryToEloquentClosures([
                'search' => function (&$eloquent, $query)
                {
                    $eloquent = $eloquent->where('title', 'LIKE', "%{$query['search']}%");
                }
            ]);

        parent::__construct();
    }

    public function store(array $data, callable $storing = null): mixed
    {
        if(TeacherSkillModel::where('teacher_id', '=', $data['teacher_id'])->count() >= 50)
        {
            throw new CustomException("Maximum Teacher Work Experiences Reached (50) ", 1002, 400);
        }
        return parent::store($data, $storing); // TODO: Change the autogenerated stub
    }

}
