<?php

namespace App\KeyValueConfigs;

use Genocide\Radiocrud\Services\KeyValueConfigService;

class AboutUs extends KeyValueConfigService
{
    protected string $key = 'about_us';

    protected array $default_values = [
        'text' => null,
        'image' => null,
        'video' => null,
    ];

    protected array|string $validationRule = [
        'text' => ['nullable', 'string', 'max:25000'],
        'image' => ['file', 'mimes:png,jpg,jpeg,svg', 'max:5000'],
        'video' => ['file', 'mimes:mp4,webm,ogg,3gp,3g2,3gpp,3gpp2', 'max:10000'],
    ];

    protected array $casts = [
        'image' => ['file'],
        'video' => ['file'],
    ];

    public function updateHelper(array $new_general_value): bool
    {
        cache()->forget('homePage');

        return parent::updateHelper($new_general_value); // TODO: Change the autogenerated stub
    }
}

